version: '3.9'
services:
  nginx:
    image: coc0a25/next-nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # for debug
      - ./log/nginx:/log/nginx
    environment:
      - SERVER1=nest1
      - SERVER2=nest2
      - SERVER3=nest3
      - SERVER4=nest4
    ports:
      - 10000:80
      # - 80:80 # for production
    deploy:
      # some docker swarm config
  db:
    image: postgres:14-alpine
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=skku
      - POSTGRES_USER=skku
      - POSTGRES_DB=skku
    ports:
      - 20000:5432
  # redis:
  # rabbitmq:
  backend1:
    image: coc0a25/next-backend:dev
    container_name: nest1
    restart: unless-stopped
    ports:
      - 10010:3000
    # environment:
    #   - POSTGRES_PASSWORD=skku
    #   - POSTGRES_USER=skku
    #   - POSTGRES_DB=skku
    #   - POSTGRES_HOST=localhost
    #   - POSTGRES_PORT=20000
  # backend2:
  #   image: coc0a25/next-backend:dev
  #   container_name: nest2
  #   restart: unless-stopped
  #   ports:
  #     - 10002:3000
  # backend3:
  #   image: coc0a25/next-backend:dev
  #   container_name: nest3
  #   restart: unless-stopped
  #   ports:
  #     - 10003:3000
  # backend4:
  #   image: coc0a25/next-backend:dev
  #   container_name: nest4
  #   restart: unless-stopped
  #   ports:
  #     - 10004:3000
  # judge-manager:
  #   image: coc0a25/judge-manager:dev
