version: '3.9'
services:
  nginx:
    image: coc0a25/next-nginx:dev
    container_name: next-nginx
    restart: unless-stopped
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/log/nginx
    environment:
      - SERVER1=next-nest1
      - SERVER2=next-nest2
      - SERVER3=next-nest3
      - SERVER4=next-nest4
    ports:
      - 10000:80
      # - 80:80 # for production
    deploy:
      # some docker swarm config
  backend1:
    image: coc0a25/next-backend:dev
    container_name: next-nest1
    restart: unless-stopped
    ports:
      - 10001:3000
  backend2:
    image: coc0a25/next-backend:dev
    container_name: next-nest2
    restart: unless-stopped
    ports:
      - 10002:3000
  backend3:
    image: coc0a25/next-backend:dev
    container_name: next-nest3
    restart: unless-stopped
    ports:
      - 10003:3000
  backend4:
    image: coc0a25/next-backend:dev
    container_name: next-nest4
    restart: unless-stopped
    ports:
      - 10004:3000
  # db:
  #   image: postgres:alpine
  #   restart: unless-stopped
  # redis:
  # rabbitmq:
  judge-manager:
    image: coc0a25/judge-manager:dev
